### ISSUE TITLE
Плагин fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by x8core** [samdark/yii2-minimal#12]
А зачем этот плагин для композера нужно устанавливать? 
 ```
composer global require "fxp/composer-asset-plugin:1.0.0"
```
Даже для этого шаблона?
Удовлетворять зависимости в лице bower пакетов, которые я не буду юзать в этом шаблоне?
Или я просто не смогу установить Yii2 через композер так как он обязательно требует:
```
bower-asset/jquery: 2.1.*@stable | 1.11.*@stable
bower-asset/jquery.inputmask: 3.1.*
bower-asset/punycode: 1.3.*
bower-asset/yii2-pjax: >=2.0.1
```

Есть способ установить Yii2 через композер игнорируя зависимости bower-asset пакетов?

**Comment by samdark** [comment]
Для любого. Нет, по-другому никак пока.
