### ISSUE TITLE
Issue giving after Installing RBAC in yii2 minimal 

### ISSUE THREAD

**Issue by rabesh** [samdark/yii2-minimal#14]
After installing yii2 RBAC as per instruction given in yii2 RBAC, while accessing different URLS provided by RBAC it gives error
![image](https://user-images.githubusercontent.com/6636647/49281050-af2bb280-f4b3-11e8-998b-92f31ef01200.png)
URL of YII2 RBAC -> https://github.com/yii2mod/yii2-rbac

**Comment by samdark** [comment]
That's not an issue of the template.
